### ISSUE TITLE
Widget settings show incorrect days until trial expired.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-financial-table#101]
Widget settings is showing 30 days until trial expired - http://www.screencast.com/t/oleozSue

Store shows 29 days until trial expired - http://www.screencast.com/t/kwRINzCdq

**Comment by alex-deaconu** [comment]
@btfrise this is not an issue with the Widget, but with the Subscription Status component itself: https://github.com/Rise-Vision/component-subscription-status. Thanks.

**Comment by btfrise** [comment]
@alex-deaconu Thanks, I'll close this and open in the correct repo.
