### ISSUE TITLE
Ticker LPSN.O is not working

### ISSUE THREAD

**Issue by shmulikgazit** [Rise-Vision/widget-financial-table#103]
Hi,

When you look for LPSN or Liveperson, LPSN.O is coming back as an instrument to add.
Once added, it displays "invalid".

Liveperson is both on Nasdac and Tel-Aviv exchanges.

Thanks.

**Comment by btfrise** [comment]
@shmulikgazit Thanks for bringing this up. This is not an issue with our Widget, but instead with our data feed. One of our technicians has looked into the issue and remedied the situation.

In the future, if you happen to see invalid symbols displayed on your presentations, please make us aware of the issue at community.risevision.com thanks!
