### ISSUE TITLE
Unable to view values (ie NYSE) 

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/widget-financial-table#104]
User has custom template code added into the new Editor, with some elements created on the new Editor (ie Placeholders).  When the user is adding the Premium Rise Financial Table widget they are not able to view the widget data incl dummy data.

Pres ID 003f2ca3-d313-43fa-8ef7-5d9918efeae4 
CID 7e3a5ff8-13ff-4a5f-a792-9af928b3cbc3

**What I've done to troubleshoot**

1. Edited the existing Placeholder by adding a new Playlist (the premium financial widget).   The change is not reflected on preview after save/publish.

2. Created a new Placeholder (with the widget) and placed it above the user's existing Placeholder and also edited the Z number.  The change is not reflected on preview after save/publish.

3. Created a new Placeholder (using another widget - the text one).  The change is reflected but it's only appearing briefly in the user's presentation.

4. Edited another Placeholder (at text based one), the change is reflected on save/publish/preview.

**What the user has done to try to troubleshoot this:**

1. Created a new presentation in the Editor and added the widget.

2. Added some of their template code from the previous presentation.

3. On save/publish/preview they report being able to see the widget.

4. When they change the Placeholder's name, they report the presentation breaking.

**Expected Results**

I expected the widget to work:

1. When added as a new Placeholder on top of an existing Placeholder.

2. When added within an existing Placeholder (in the Playlist area).

3. When the Placeholder name has been changed for the widget.

---

Other comments (from RD who has also been working with the user)
- It happens if the widget isn't configured, but it also happens sometimes even if it is configured.

**Comment by alanclayton** [comment]
Widget not available in the store. Won't fix.
