### ISSUE TITLE
Trial Available - Start Trial link broken.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/widget-financial-table#99]
When clicking start trial in the widget configuration, the link does not function. 

http://www.screencast.com/t/WcZwy4jjM

**Comment by alex-deaconu** [comment]
@btfrise this issue should now be fixed as well. However, I only tested it in my local environment, I don't know how to test it in the RVA since the Widget is subscribed now (and it doesn't have the link). Thanks.
